// Curated showcase first (keeps the home page cards working).
// Everything else is a GitHub (or local) project — delete any entry you do not want shown.

export const projects = [
	{
		id: 1,
		img: 'cocktails-library.png',
		url: 'https://pere-cocktails.netlify.app',
		github: 'https://github.com/Perekada/cocktails',
		text: 'cocktail library',
		name: 'cocktails',
		description: 'Cocktail recipe library.',
		language: 'JavaScript',
		frameworks: ['JavaScript', 'React'],
		featured: true,
	},
	{
		id: 2,
		img: 'reviews.png',
		url: 'https://kadareviews.netlify.app',
		github: 'https://github.com/Perekada/Review-app',
		text: 'reviews',
		name: 'Review-app',
		description: 'Reviews UI project.',
		language: 'CSS',
		frameworks: ['JavaScript', 'CSS'],
		featured: true,
	},
	{
		id: 3,
		img: 'FAQ.png',
		url: 'https://metanewpagesfaq.netlify.app',
		github: 'https://github.com/Perekada/FAQ',
		text: 'facebook FAQ',
		name: 'FAQ',
		description: 'FAQ accordion page.',
		language: 'JavaScript',
		frameworks: ['JavaScript'],
		featured: true,
	},
	{
		id: 4,
		img: 'tours.png',
		url: 'https://perekadatours.netlify.app',
		github: 'https://github.com/Perekada/Tours-Project',
		text: 'tours',
		name: 'Tours-Project',
		description: 'Tours listing project.',
		language: 'CSS',
		frameworks: ['JavaScript', 'CSS'],
		featured: true,
	},
	{
		id: 5,
		img: 'menu.png',
		url: 'https://resturantmenu12.netlify.app',
		github: 'https://github.com/Perekada/menu',
		text: 'Resturant menu',
		name: 'menu',
		description: 'Restaurant menu UI.',
		language: 'JavaScript',
		frameworks: ['JavaScript'],
		featured: true,
	},
	{
		id: 6,
		img: 'firebaseClone.png',
		url: 'https://firebaseclone.netlify.app',
		github: 'https://github.com/Perekada/Firebase-clone',
		text: 'Firebase Clone',
		name: 'Firebase-clone',
		description: 'Firebase landing-page clone.',
		language: 'JavaScript',
		frameworks: ['JavaScript'],
		featured: true,
	},
	{
		id: 7,
		img: null,
		url: 'https://github.com/Perekada/portfolio',
		github: 'https://github.com/Perekada/portfolio',
		text: 'portfolio',
		name: 'portfolio',
		description: 'My portfolio',
		language: 'CSS',
		frameworks: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
		featured: false,
	},
	{
		id: 8,
		img: null,
		url: 'https://github.com/Perekada/Aeson-care',
		github: 'https://github.com/Perekada/Aeson-care',
		text: 'Aeson-care',
		name: 'Aeson-care',
		description: 'Aeson Care project.',
		language: 'JavaScript',
		frameworks: ['JavaScript'],
		featured: false,
	},
	{
		id: 9,
		img: null,
		url: 'https://github.com/Perekada/Johngate',
		github: 'https://github.com/Perekada/Johngate',
		text: 'Johngate',
		name: 'Johngate',
		description: 'Johngate project.',
		language: 'JavaScript',
		frameworks: ['JavaScript'],
		featured: false,
	},
	{
		id: 10,
		img: null,
		url: 'https://github.com/Perekada/producthunt-project',
		github: 'https://github.com/Perekada/producthunt-project',
		text: 'producthunt-project',
		name: 'producthunt-project',
		description: 'Product Hunt style project.',
		language: 'Python',
		frameworks: ['Python', 'Django'],
		featured: false,
	},
	{
		id: 11,
		img: null,
		url: 'https://github.com/Perekada/Projects',
		github: 'https://github.com/Perekada/Projects',
		text: 'Projects',
		name: 'Projects',
		description: 'Forked projects collection.',
		language: null,
		frameworks: [],
		featured: false,
	},
	{
		id: 12,
		img: null,
		url: 'https://github.com/Perekada/Perekada',
		github: 'https://github.com/Perekada/Perekada',
		text: 'Perekada',
		name: 'Perekada',
		description: 'Config files for my GitHub profile.',
		language: null,
		frameworks: [],
		featured: false,
	},
	{
		id: 13,
		img: null,
		url: null,
		github: null,
		text: 'CAISE payroll',
		name: 'CAISE-payroll',
		description:
			'Payroll platform monorepo (API + web). Local clone only — not in the public GitHub list.',
		language: 'TypeScript',
		frameworks: ['Next.js', 'Node', 'Prisma'],
		featured: false,
	},
	{
		id: 14,
		img: null,
		url: null,
		github: null,
		text: 'Exxforce Frontend',
		name: 'Exxforce-Frontend-',
		description:
			'Excelforce frontend (tables, forms, dashboards). Local clone only — not in the public GitHub list.',
		language: 'TypeScript',
		frameworks: ['Next.js', 'React', 'TanStack Table', 'dnd-kit'],
		featured: false,
	},
];
