import type { Metadata } from 'next';
import { Nunito, Playwrite_NZ } from 'next/font/google';
import localFont from 'next/font/local';
import { Navbar } from './components/Navbar';
import Footer from './components/Footer';
import './globals.css';
import { AppProvider } from './Context';

const Playwrite = localFont({
	src: '/fonts/PlaywriteNZGuides-Regular.ttf',
	variable: '--font-playwrite',
	display: 'swap',
});

const Playwrite_NZ_Font = Playwrite_NZ({
	variable: '--font-playwrites',
});

const nunito = Nunito({
	variable: '--font-nunito',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Joel Oyinperebo Kada - Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${Playwrite_NZ_Font.variable} ${nunito.className} ${Playwrite.className}`}>
				<AppProvider>
					<Navbar />
					<div className='mt-40'>
					{children}
					</div>
					<Footer />
				</AppProvider>
			</body>
		</html>
	);
}
